### ISSUE TITLE
As an editor I want to be able to upload judgments with non-numeric case numbers

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#1410]
```
Line number: 1476 - could not convert string to float: '46B'
None, Samson Erald vs off Grid Electronics Tanzania, Misc. Application No. 46B of 2029, Misc. Application, 46B, 2019, TZHC, https://media.tanzlii.org/files/judgments/tzhc/2021/3253/2021-tzhc-3253_1.pdf, 3253, Masara, J., 2021-05-25, TZHC-high-court-arusha-registry, [2021] TZHC 3253, 2021-05-26 00:00:00, Tawan Salim, eng, TZ, 2
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/import_export/resources.py", line 756, in import_row
self.after_import_row(row, row_result, **kwargs)
File "/app/peachjam/resources.py", line 528, in after_import_row
for case_number in self.get_case_numbers(row):
File "/app/peachjam/resources.py", line 483, in get_case_numbers
case_number_numeric = [
File "/app/peachjam/resources.py", line 484, in <listcomp>
int(float(n)) if n else None
ValueError: could not convert string to float: '46B'

Line number: 1655 - could not convert string to float: '50F'
None, Sikudhan Abdallah Mshana vs Bank of Africa Tanzania Limited, Land Case No. 50F of 2018, Land Case, 50F, 2018, TZHC, https://media.tanzlii.org/files/judgments/tzhc/2021/3173/2021-tzhc-3173_0.pdf, 3173, Gwae, J., 2021-05-12, TZHC-high-court-arusha-registry, [2021] TZHC 3173, 2021-05-17 00:00:00, Tawan Salim, eng, TZ, 2
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/import_export/resources.py", line 756, in import_row
self.after_import_row(row, row_result, **kwargs)
File "/app/peachjam/resources.py", line 528, in after_import_row
for case_number in self.get_case_numbers(row):
File "/app/peachjam/resources.py", line 483, in get_case_numbers
case_number_numeric = [
File "/app/peachjam/resources.py", line 484, in <listcomp>
int(float(n)) if n else None
ValueError: could not convert string to float: '50F'
```

**Comment by longhotsummer** [comment]
An argument against this is that users enter incorrect details like `o` instead of `0`.
